services:
  # Order Service
  order-service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    image: order-service:latest
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:orderdb
      - INVENTORY_SERVICE_URL=http://inventory-service:8082
      - CUSTOMER_SERVICE_URL=http://customer-service:8083
    networks:
      - microservices-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8081/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - inventory-service
      - customer-service

  # Inventory Service
  inventory-service:
    build:
      context: ./inventory_service
      dockerfile: Dockerfile
    image: inventory-service:latest
    container_name: inventory-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:inventorydb
    networks:
      - microservices-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8082/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Customer Service
  customer-service:
    build:
      context: ./customer_service
      dockerfile: Dockerfile
    image: customer-service:latest
    container_name: customer-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:customerdb
    networks:
      - microservices-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8083/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  microservices-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
