apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # Base64 encoded values
  # username: postgres (cG9zdGdyZXM=)
  # password: postgres (cG9zdGdyZXM=)
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Example API keys or tokens (base64 encoded)
  # api-key: my-secret-key (bXktc2VjcmV0LWtleQ==)
  api-key: bXktc2VjcmV0LWtleQ==
