apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
data:
  application.properties: |
    spring.application.name=customer-service
    server.port=8083

    # Actuator
    management.endpoints.web.exposure.include=health,info,prometheus
    management.endpoint.health.show-details=always

    # Logging
    logging.level.root=INFO
    logging.level.com.orch.customer_service=DEBUG
