apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
data:
  application.properties: |
    spring.application.name=inventory-service
    server.port=8082

    # Actuator
    management.endpoints.web.exposure.include=health,info,prometheus
    management.endpoint.health.show-details=always

    # Logging
    logging.level.root=INFO
    logging.level.com.orch.inventory_service=DEBUG
